### ISSUE TITLE
Error: Plugin did not respond terraform-provider-megaport_v0.2.10

### ISSUE THREAD

**Issue by CarmineDeloitte** [megaport/terraform-provider-megaport#38]
Hello, 

I'm using the terraform megaport provider to create an aws connection.
When I try to do a terraform apply, the terraform-provider-megaport_v0.2.10 crush with this error

```
megaport_aws_connection.aws_vxc: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with megaport_aws_connection.aws_vxc,
│   on main.tf line 12, in resource "megaport_aws_connection" "aws_vxc":
│   12: resource "megaport_aws_connection" "aws_vxc" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-megaport_v0.2.10 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 65 [running]:
github.com/megaport/megaportgo/service/vxc.(*VXC).BuyAWSVXC(0xc000533940, {0xc0003ce210, 0x24}, {0xc0003d2120, 0x1b}, 0x3e8, {0xbf, {{0x0, 0x0, 0x0}}}, ...)
        github.com/megaport/megaportgo@v0.1.16-beta/service/vxc/aws.go:63 +0x271
github.com/megaport/terraform-provider-megaport/resource_megaport.resourceMegaportAWSConnectionCreate(0xbea720, {0xbda680, 0xc00028b080})
        github.com/megaport/terraform-provider-megaport/resource_megaport/resource_megaport_aws_connection.go:76 +0x6e5
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0004eaea0, 0xc0000d49b0, 0xc00007a720, {0xbda680, 0xc00028b080})
        github.com/hashicorp/terraform-plugin-sdk@v1.9.1/helper/schema/resource.go:310 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00019c000, 0xc00025ba48, 0xcd50d4, 0xf)
        github.com/hashicorp/terraform-plugin-sdk@v1.9.1/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000c0018, {0xc00031a000, 0x4b41a6}, 0xc00031a000)
        github.com/hashicorp/terraform-plugin-sdk@v1.9.1/internal/helper/plugin/grpc_provider.go:885 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xca3580, 0xc0000c0018}, {0xe3bcb0, 0xc00013af90}, 0xc0000c2540, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.9.1/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004c4480, {0xe481c8, 0xc000018000}, 0xc0003d6200, 0xc000643050, 0x13614e0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0004c4480, {0xe481c8, 0xc000018000}, 0xc0003d6200, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xef

Error: The terraform-provider-megaport_v0.2.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Here my main.tf

```tf
terraform {
  required_providers {
    megaport = {
      source  = "megaport/megaport"
      version = ">=0.2.9"
    }  
  }
}

provider "megaport" {
  username              = "my@email"
  password              = "mypass"
  accept_purchase_terms = true
  delete_ports          = true
  environment           = "staging"
}

#this port alredy exist and I imported it with terraform import
resource "megaport_port" "TF_TEST" {
  #(resource arguments)
  location_id = 130
  port_name = "TF_TEST"
  port_speed =  10000
  lag = false
  lag_port_count  = 0
  term = 12

}

resource "megaport_aws_connection" "aws_vxc" {
  vxc_name   = "Terraform Example - AWS VXC"
  rate_limit = 1000

  a_end {
    port_id        = megaport_port.TF_TEST.id
    requested_vlan = 191

  }

  csp_settings {
    requested_product_id = megaport_port.TF_TEST.id
    requested_asn        = 64550
    amazon_asn           = 64551
    amazon_account       = "11111111" 
    hosted_connection = true
  }
}
```

**Comment by CarmineDeloitte** [comment]
This is my tf output when doing terraform apply 

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # megaport_aws_connection.aws_vxc will be created
  + resource "megaport_aws_connection" "aws_vxc" {
      + admin_locked        = (known after apply)
      + aws_id              = (known after apply)
      + b_end               = (known after apply)
      + company_name        = (known after apply)
      + create_date         = (known after apply)
      + created_by          = (known after apply)
      + id                  = (known after apply)
      + live_date           = (known after apply)
      + locked              = (known after apply)
      + provisioning_status = (known after apply)
      + rate_limit          = 1000
      + vxc_internal_type   = "aws"
      + vxc_name            = "Terraform Example - AWS VXC"
      + vxc_type            = (known after apply)

      + a_end {
          + assigned_asn   = (known after apply)
          + assigned_vlan  = (known after apply)
          + location       = (known after apply)
          + name           = (known after apply)
          + owner_uid      = (known after apply)
          + port_id        = "380c747b-c647-4a27-93f9-65d13aada2d3"
          + requested_vlan = 191
        }

      + csp_settings {
          + amazon_account       = "11111111"
          + amazon_asn           = 64551
          + assigned_asn         = (known after apply)
          + hosted_connection    = true
          + requested_asn        = 64550
          + requested_product_id = "380c747b-c647-4a27-93f9-65d13aada2d3"
          + visibility           = "private"
        }
    }
```

**Comment by flackon** [comment]
It looks like you're missing config for the AWS partner port you're connecting to.

Try adding for example:

`data "megaport_location" "syd_gs" {
  name = "Global Switch Sydney West"
}

data "megaport_partner_port" "aws_port" {
  company_name   = "AWS"
  connect_type   = "AWSHC"
  product_name   = "Asia Pacific (Sydney) (ap-southeast-2)"
  diversity_zone = "red"
  location_id    = data.megaport_location.syd_gs.id
}`

Then update requested_product_id to `requested_product_id = data.megaport_partner_port.aws_port.id`

**Comment by CarmineDeloitte** [comment]
Thanks a lot! I totally miss this point, took a while to figure it out.
My confusion was the megaport_port and the aws_port (the partner_port).
